### ISSUE TITLE
No reference to BlindXfer in SoftKeys.xml

### ISSUE THREAD

**Issue by cyberws** [usecallmanagernz/tftpboot#1]
Hi,

I have recently configured a Cisco CP-8851-K9 V11 handset using TFTP configuration files with settings I had found from various sources on the internet. None of the datasets I found, until just now, contained a SoftKeys file. On my phone the Do Not Disturb, Hold and Transfer softkeys were always missing.

The SoftKeys.xml file in this Branch has enabled me to get those softkeys to now display and operate and they should and for this I am very grateful.

However, I have seen several training videos showing blind transfers where a "BlindXfer" software exists, which enable transfer to a third party without the call being answered. For example this video - [User Training on Cisco 8800 Series Handsets - YouTube Video](https://www.youtube.com/watch?v=gTqiGuJCnsM&t=199s). Is this something proprietary to Webex perhaps? 

Does anyone know how to achieve this functionality?

Thanks in advance for any assistance AND for this helpful repo in the first place.

Using sip88xx.14-2-1-0201-40 firmware and UK SIP provider Voipfone.

**Comment by gareth-palmer** [comment]
Those examples appear to show a phone that is running the Multi-platform firmware.
